"""Persistent modelling projects: the single source of truth of a model (decision D-004)."""

from buildup.project.export import (
    GENERATOR,
    SKELETON_MODES,
    ExportResult,
    SkeletonMode,
    build_assembly,
    export_project,
)
from buildup.project.model import (
    EDIT_MODES,
    FINISHES,
    MAX_PARTS,
    Axle,
    Color,
    EditMode,
    Part,
    Project,
    WheelInfo,
    WheelLayout,
    parse_finish,
    parse_material,
)
from buildup.project.names import (
    ProjectError,
    check_mod_name,
    check_name,
    check_project_name,
    default_mod_name,
)
from buildup.project.shapes import (
    WORLD_MAX,
    WORLD_MIN,
    Shape,
    box_shape,
    clip_to_world,
    cylinder_shape,
    edge_cut_shape,
    ellipsoid_shape,
    wedge_shape,
)
from buildup.project.store import MAX_HISTORY, ProjectFileError, ProjectStore

__all__ = [
    "EDIT_MODES",
    "FINISHES",
    "GENERATOR",
    "MAX_HISTORY",
    "MAX_PARTS",
    "SKELETON_MODES",
    "WORLD_MAX",
    "WORLD_MIN",
    "Axle",
    "Color",
    "EditMode",
    "ExportResult",
    "Part",
    "Project",
    "ProjectError",
    "ProjectFileError",
    "ProjectStore",
    "Shape",
    "SkeletonMode",
    "WheelInfo",
    "WheelLayout",
    "box_shape",
    "build_assembly",
    "check_mod_name",
    "check_name",
    "check_project_name",
    "clip_to_world",
    "cylinder_shape",
    "default_mod_name",
    "edge_cut_shape",
    "ellipsoid_shape",
    "export_project",
    "parse_finish",
    "parse_material",
    "wedge_shape",
]
